repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fq-processing-nf_logo_light.png
    - docs/images/nf-core-fq-processing-nf_logo_light.png
    - docs/images/nf-core-fq-processing-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fq-processing-nf_logo_light.png
    - docs/images/nf-core-fq-processing-nf_logo_light.png
    - docs/images/nf-core-fq-processing-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - CITATIONS.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - assets/multiqc_config.yml
    - nextflow_schema.json
  readme:
    - nextflow_badge
    - nfcore_template_badge
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: andersenlab
  name: fq-processing-nf
  description: A nextflow for taking raw sequencing reads (fastqs), performing trimming,
    species identification, mapping, and genotype checking
  author: Michael Sauria
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - github_badges
    - igenomes
    - multiqc
    - fastqc
    - nf_schema
    - seqera_platform
    - gpu
    - codespaces
    - vscode
    - citations
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
